package org.firstinspires.ftc.teamcode.hardware.robots;

public enum TurretBotPosition {
  INTAKE_POSITION,
  INTAKE_HOVER_POSITION,
  SHARED_CLOSE_POSITION,
  SHARED_MIDDLE_POSITION,
  SHARED_FAR_POSITION,
  TIPPED_CLOSE_POSITION,
  TIPPED_MIDDLE_POSITION,
  TIPPED_FAR_POSITION,
  ALLIANCE_BOTTOM_POSITION,
  ALLIANCE_MIDDLE_POSITION,
  ALLIANCE_TOP_POSITION,
  TEAM_MARKER_GRAB_POSITION,
  TEAM_MARKER_DEPOSIT_POSITION
}
